
{ "_id": { "$oid": "6336bae7b3cc2365579e2dd2" }, "movieName": "The Conjuring: The Devil Made Me Do It", "describe": "Paranormal investigators Ed and Lorraine Warren are faced with one of their most challenging cases when a murder suspect claims to be possessed by a demon. The movie is also available in 4K on BMS stream.", "age": "15+", "img": "https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@heart_202006300400.png,ox-24,oy-617,ow-29:ote-NzAlICAxMGsgdm90ZXM%3D,ots-29,otc-FFFFFF,oy-612,ox-70/et00122455-vxkfujkzjy-portrait.jpg", "language": "Hindi", "categaries": ["Action", "Horror", "Thriller"], "Ontheater": true, "shows": ["9:30 am", "1:00 pm", "4:00 pm", "8:00 pm", "10:00 pm"], 
"seating_arrangement": [
    { 
        "area": "Gold", 
        "price": "100", 
    "seats": [
    { 
        "row": "A", 
        "column": [
            { "row":"A","price":"100","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"A","price":"100","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"A","price":"100","column_no": "11", "visibility": "hidden", "status": "Booked" }, 
            { "row":"A","price":"100","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "13", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "14", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "16", "visibility": "hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "17", "visibility": "hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "18", "visibility": "hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "19", "visibility": "hidden", "status": "Available" }, 
            { "row":"A","price":"100","column_no": "20", "visibility": "hidden", "status": "Available" }
            
        ] 
    }, 
    { 
        "row": "B", 
        "column": [
            { "row":"B","price":"100","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"B","price":"100","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"B","price":"100","column_no": "11", "visibility": "hidden", "status": "Booked" }, 
            { "row":"B","price":"100","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "13", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "14", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "16", "visibility": "hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "17", "visibility": "hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "18", "visibility": "hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "19", "visibility": "hidden", "status": "Available" }, 
            { "row":"B","price":"100","column_no": "20", "visibility": "hidden", "status": "Available" }
            
            ] }, 
    { 
        "row": "C", 
        "column": [
            { "row":"C","price":"100","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"C","price":"100","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"C","price":"100","column_no": "11", "visibility": "hidden", "status": "Booked" }, 
            { "row":"C","price":"100","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "13", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "14", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "16", "visibility": "hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "17", "visibility": "hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "18", "visibility": "hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "19", "visibility": "hidden", "status": "Available" }, 
            { "row":"C","price":"100","column_no": "20", "visibility": "hidden", "status": "Available" }
            
            
            ] }, 
    { 
        "row": "D", 
        "column": [
            { "row":"D","price":"100","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"D","price":"100","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"D","price":"100","column_no": "11", "visibility": "hidden", "status": "Booked" }, 
            { "row":"D","price":"100","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "13", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "14", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "16", "visibility": "hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "17", "visibility": "hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "18", "visibility": "hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "19", "visibility": "hidden", "status": "Available" }, 
            { "row":"D","price":"100","column_no": "20", "visibility": "hidden", "status": "Available" }
            
            ] }, 
    { 
        "row": "E", "column": [
            { "row":"E","price":"100","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"E","price":"100","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"E","price":"100","column_no": "11", "visibility": "hidden", "status": "Booked" }, 
            { "row":"E","price":"100","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "13", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "14", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "16", "visibility": "hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "17", "visibility": "hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "18", "visibility": "hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "19", "visibility": "hidden", "status": "Available" }, 
            { "row":"E","price":"100","column_no": "20", "visibility": "hidden", "status": "Available" }
            
            ] }] }, 
    { "area": "Silver", "price": "50", 
        
        "seats": [
    { 
        "row": "F", 
        "column": [
            { "row":"F","price":"50","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"F","price":"50","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"F","price":"50","column_no": "11", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"F","price":"50","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "13", "visibility": "hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "14", "visibility": "hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "16", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "17", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "18", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "19", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"F","price":"50","column_no": "20", "visibility": "not_hidden", "status": "Available" }

            ] }, 
    { 
        "row": "G", "column": [
            { "row":"G","price":"50","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"G","price":"50","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"G","price":"50","column_no": "11", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"G","price":"50","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "13", "visibility": "hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "14", "visibility": "hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "16", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "17", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "18", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "19", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"G","price":"50","column_no": "20", "visibility": "not_hidden", "status": "Available" }
            
            ] }, 
    { 
        "row": "H", 
        "column": [
            { "row":"H","price":"50","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"H","price":"50","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"H","price":"50","column_no": "11", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"H","price":"50","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "13", "visibility": "hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "14", "visibility": "hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "16", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "17", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "18", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "19", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"H","price":"50","column_no": "20", "visibility": "not_hidden", "status": "Available" }
            
            ] }, 
    { 
        "row": "I", 
        "column": [
            { "row":"I","price":"50","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"I","price":"50","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"I","price":"50","column_no": "11", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"I","price":"50","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "13", "visibility": "hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "14", "visibility": "hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "16", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "17", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "18", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "19", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"I","price":"50","column_no": "20", "visibility": "not_hidden", "status": "Available" }
            
            ] }, 
    { 
        "row": "J", "column": [
            { "row":"J","price":"50","column_no": "1", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"J","price":"50","column_no": "2", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "3", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "4", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "5", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "6", "visibility": "hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "7", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "8", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "9", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "10", "visibility": "not_hidden", "status": "Available" },
            { "row":"J","price":"50","column_no": "11", "visibility": "not_hidden", "status": "Booked" }, 
            { "row":"J","price":"50","column_no": "12", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "13", "visibility": "hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "14", "visibility": "hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "15", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "16", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "17", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "18", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "19", "visibility": "not_hidden", "status": "Available" }, 
            { "row":"J","price":"50","column_no": "20", "visibility": "not_hidden", "status": "Available" }
            
            ] }] }] }