export default function handler(req, res) {
    res.status(200).json(seats)
  }

  const seats=
  [
      {
          id:"1",
          movieName:"The Conjuring: The Devil Made Me Do It",
          "describe":"Paranormal investigators Ed and Lorraine Warren are faced with one of their most challenging cases when a murder suspect claims to be possessed by a demon. The movie is also available in 4K on BMS stream.",
          "age":"15+",
          "img":"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@heart_202006300400.png,ox-24,oy-617,ow-29:ote-NzAlICAxMGsgdm90ZXM%3D,ots-29,otc-FFFFFF,oy-612,ox-70/et00122455-vxkfujkzjy-portrait.jpg",
          "start":"10:15 am",
          "end":"12:30 pm",
          "language":"Hindi",
          "categaries":["Action"," Horror ,",' Thriller'],
          "Ontheater":true,
          seats:[{
            "id": "96-996-0030",
            "seatNumber": 1,
            "price": "$425.58",
            "booked": true,
            "disable": true
          }, {
            "id": "44-302-9605",
            "seatNumber": 2,
            "price": "$318.12",
            "booked": false,
            "disable": false
          }, {
            "id": "30-949-9801",
            "seatNumber": 3,
            "price": "$398.85",
            "booked": true,
            "disable": true
          }, {
            "id": "99-271-8024",
            "seatNumber": 4,
            "price": "$362.60",
            "booked": true,
            "disable": false
          }, {
            "id": "78-448-3579",
            "seatNumber": 5,
            "price": "$476.61",
            "booked": true,
            "disable": true
          }, {
            "id": "91-727-3811",
            "seatNumber": 6,
            "price": "$434.88",
            "booked": false,
            "disable": false
          }, {
            "id": "33-095-8948",
            "seatNumber": 7,
            "price": "$394.31",
            "booked": false,
            "disable": true
          }, {
            "id": "82-386-1808",
            "seatNumber": 8,
            "price": "$499.00",
            "booked": false,
            "disable": false
          }, {
            "id": "01-846-4341",
            "seatNumber": 9,
            "price": "$315.91",
            "booked": true,
            "disable": false
          }, {
            "id": "08-332-0342",
            "seatNumber": 10,
            "price": "$385.85",
            "booked": false,
            "disable": true
          }, {
            "id": "93-859-3731",
            "seatNumber": 11,
            "price": "$390.92",
            "booked": true,
            "disable": false
          }, {
            "id": "15-222-1779",
            "seatNumber": 12,
            "price": "$389.68",
            "booked": false,
            "disable": true
          }, {
            "id": "87-089-9284",
            "seatNumber": 13,
            "price": "$451.96",
            "booked": false,
            "disable": true
          }, {
            "id": "44-300-5004",
            "seatNumber": 14,
            "price": "$323.17",
            "booked": false,
            "disable": true
          }, {
            "id": "10-788-1545",
            "seatNumber": 15,
            "price": "$334.92",
            "booked": true,
            "disable": false
          }, {
            "id": "89-248-6395",
            "seatNumber": 16,
            "price": "$476.83",
            "booked": true,
            "disable": true
          }, {
            "id": "69-108-4567",
            "seatNumber": 17,
            "price": "$419.59",
            "booked": false,
            "disable": false
          }, {
            "id": "96-390-4151",
            "seatNumber": 18,
            "price": "$421.39",
            "booked": false,
            "disable": true
          }, {
            "id": "65-152-0962",
            "seatNumber": 19,
            "price": "$362.16",
            "booked": true,
            "disable": true
          }, {
            "id": "88-290-8544",
            "seatNumber": 20,
            "price": "$327.33",
            "booked": false,
            "disable": true
          }, {
            "id": "02-390-0626",
            "seatNumber": 21,
            "price": "$390.83",
            "booked": false,
            "disable": true
          }, {
            "id": "98-402-4000",
            "seatNumber": 22,
            "price": "$309.93",
            "booked": false,
            "disable": false
          }, {
            "id": "08-422-1342",
            "seatNumber": 23,
            "price": "$408.67",
            "booked": false,
            "disable": false
          }, {
            "id": "77-479-6497",
            "seatNumber": 24,
            "price": "$390.06",
            "booked": true,
            "disable": false
          }, {
            "id": "54-425-1207",
            "seatNumber": 25,
            "price": "$474.31",
            "booked": true,
            "disable": false
          }, {
            "id": "33-892-4494",
            "seatNumber": 26,
            "price": "$436.00",
            "booked": true,
            "disable": true
          }, {
            "id": "95-393-1437",
            "seatNumber": 27,
            "price": "$335.23",
            "booked": false,
            "disable": false
          }, {
            "id": "36-523-5324",
            "seatNumber": 28,
            "price": "$469.68",
            "booked": false,
            "disable": false
          }, {
            "id": "48-859-8178",
            "seatNumber": 29,
            "price": "$319.70",
            "booked": false,
            "disable": false
          }, {
            "id": "74-142-3716",
            "seatNumber": 30,
            "price": "$417.58",
            "booked": true,
            "disable": false
          }, {
            "id": "57-916-7766",
            "seatNumber": 31,
            "price": "$413.27",
            "booked": false,
            "disable": false
          }, {
            "id": "74-781-5791",
            "seatNumber": 32,
            "price": "$323.66",
            "booked": false,
            "disable": false
          }, {
            "id": "46-230-5311",
            "seatNumber": 33,
            "price": "$331.89",
            "booked": false,
            "disable": false
          }, {
            "id": "19-371-8800",
            "seatNumber": 34,
            "price": "$483.92",
            "booked": true,
            "disable": true
          }, {
            "id": "45-028-1500",
            "seatNumber": 35,
            "price": "$375.56",
            "booked": true,
            "disable": false
          }, {
            "id": "51-814-0847",
            "seatNumber": 36,
            "price": "$460.98",
            "booked": true,
            "disable": false
          }, {
            "id": "57-860-0496",
            "seatNumber": 37,
            "price": "$349.00",
            "booked": true,
            "disable": false
          }, {
            "id": "13-572-4898",
            "seatNumber": 38,
            "price": "$487.75",
            "booked": true,
            "disable": false
          }, {
            "id": "11-873-2977",
            "seatNumber": 39,
            "price": "$323.16",
            "booked": true,
            "disable": false
          }, {
            "id": "61-723-2298",
            "seatNumber": 40,
            "price": "$424.48",
            "booked": true,
            "disable": true
          }, {
            "id": "98-051-0459",
            "seatNumber": 41,
            "price": "$351.61",
            "booked": false,
            "disable": true
          }, {
            "id": "24-698-7605",
            "seatNumber": 42,
            "price": "$493.94",
            "booked": true,
            "disable": true
          }, {
            "id": "89-150-1793",
            "seatNumber": 43,
            "price": "$320.39",
            "booked": true,
            "disable": false
          }, {
            "id": "20-563-3415",
            "seatNumber": 44,
            "price": "$471.06",
            "booked": false,
            "disable": false
          }, {
            "id": "25-306-7222",
            "seatNumber": 45,
            "price": "$392.20",
            "booked": true,
            "disable": true
          }, {
            "id": "90-383-5635",
            "seatNumber": 46,
            "price": "$328.95",
            "booked": false,
            "disable": true
          }, {
            "id": "86-047-3017",
            "seatNumber": 47,
            "price": "$324.27",
            "booked": false,
            "disable": true
          }, {
            "id": "15-014-6169",
            "seatNumber": 48,
            "price": "$328.56",
            "booked": false,
            "disable": true
          }, {
            "id": "78-190-6685",
            "seatNumber": 49,
            "price": "$307.22",
            "booked": true,
            "disable": false
          }, {
            "id": "87-150-9751",
            "seatNumber": 50,
            "price": "$367.04",
            "booked": false,
            "disable": true
          }, {
            "id": "31-002-0455",
            "seatNumber": 51,
            "price": "$428.53",
            "booked": true,
            "disable": true
          }, {
            "id": "42-899-7653",
            "seatNumber": 52,
            "price": "$332.07",
            "booked": true,
            "disable": false
          }, {
            "id": "49-619-3891",
            "seatNumber": 53,
            "price": "$311.64",
            "booked": false,
            "disable": false
          }, {
            "id": "73-937-4454",
            "seatNumber": 54,
            "price": "$365.88",
            "booked": false,
            "disable": true
          }, {
            "id": "44-309-1793",
            "seatNumber": 55,
            "price": "$414.55",
            "booked": false,
            "disable": true
          }, {
            "id": "92-280-5812",
            "seatNumber": 56,
            "price": "$373.23",
            "booked": false,
            "disable": true
          }, {
            "id": "26-125-1485",
            "seatNumber": 57,
            "price": "$465.33",
            "booked": false,
            "disable": false
          }, {
            "id": "42-249-8725",
            "seatNumber": 58,
            "price": "$379.99",
            "booked": true,
            "disable": true
          }, {
            "id": "40-146-4878",
            "seatNumber": 59,
            "price": "$451.21",
            "booked": false,
            "disable": true
          }, {
            "id": "80-307-7275",
            "seatNumber": 60,
            "price": "$418.76",
            "booked": false,
            "disable": true
          }]
      },
      {
          id:"2",
          movieName:"Bunty Aur Babli 2",
          describe:"Yash Raj Film`s production BUNTY AUR BABLI 2 has been completely rebooted to be set in today`s day and age. The much-anticipated sequel will see a huge time leap of 10 years. Starring Siddhant Chaturvedi, Sharvari Wagh, Saif Ali Khan and Rani Mukerji in prominent roles. It is a drama written and directed by Varun V. Sharma.",
          age:"7+",
          img:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@heart_202006300400.png,ox-24,oy-617,ow-29:ote-NjAlICA0ayB2b3Rlcw%3D%3D,ots-29,otc-FFFFFF,oy-612,ox-70/et00127081-xgeelsqdyw-portrait.jpg",
          start:"01:15",
          end:"03:30",
          language:"Hindi",
          categaries:['Comedy','Crime'],
          Ontheater:true,
          seats:[{
            "id": "14-228-2327",
            "seatNumber": 1,
            "price": "$492.68",
            "booked": false,
            "disable": false
          }, {
            "id": "92-165-8951",
            "seatNumber": 2,
            "price": "$403.87",
            "booked": false,
            "disable": true
          }, {
            "id": "54-485-8450",
            "seatNumber": 3,
            "price": "$372.60",
            "booked": true,
            "disable": false
          }, {
            "id": "20-265-1604",
            "seatNumber": 4,
            "price": "$354.98",
            "booked": false,
            "disable": true
          }, {
            "id": "52-169-5907",
            "seatNumber": 5,
            "price": "$482.55",
            "booked": false,
            "disable": true
          }, {
            "id": "08-839-6591",
            "seatNumber": 6,
            "price": "$406.52",
            "booked": true,
            "disable": false
          }, {
            "id": "76-673-4356",
            "seatNumber": 7,
            "price": "$402.18",
            "booked": true,
            "disable": true
          }, {
            "id": "95-481-1826",
            "seatNumber": 8,
            "price": "$393.89",
            "booked": false,
            "disable": false
          }, {
            "id": "71-260-6773",
            "seatNumber": 9,
            "price": "$473.17",
            "booked": false,
            "disable": false
          }, {
            "id": "83-660-9176",
            "seatNumber": 10,
            "price": "$492.52",
            "booked": true,
            "disable": true
          }, {
            "id": "33-010-8969",
            "seatNumber": 11,
            "price": "$431.80",
            "booked": true,
            "disable": false
          }, {
            "id": "96-300-0203",
            "seatNumber": 12,
            "price": "$345.02",
            "booked": false,
            "disable": true
          }, {
            "id": "75-498-3077",
            "seatNumber": 13,
            "price": "$438.61",
            "booked": true,
            "disable": false
          }, {
            "id": "23-142-4405",
            "seatNumber": 14,
            "price": "$385.31",
            "booked": false,
            "disable": false
          }, {
            "id": "84-546-9793",
            "seatNumber": 15,
            "price": "$342.24",
            "booked": true,
            "disable": true
          }, {
            "id": "47-584-7372",
            "seatNumber": 16,
            "price": "$397.32",
            "booked": true,
            "disable": false
          }, {
            "id": "07-823-0144",
            "seatNumber": 17,
            "price": "$487.90",
            "booked": false,
            "disable": false
          }, {
            "id": "55-973-9878",
            "seatNumber": 18,
            "price": "$344.86",
            "booked": true,
            "disable": false
          }, {
            "id": "38-461-9079",
            "seatNumber": 19,
            "price": "$413.50",
            "booked": true,
            "disable": false
          }, {
            "id": "39-491-5526",
            "seatNumber": 20,
            "price": "$477.50",
            "booked": false,
            "disable": false
          }, {
            "id": "71-110-8997",
            "seatNumber": 21,
            "price": "$315.81",
            "booked": true,
            "disable": true
          }, {
            "id": "72-521-5730",
            "seatNumber": 22,
            "price": "$418.75",
            "booked": true,
            "disable": false
          }, {
            "id": "09-333-5685",
            "seatNumber": 23,
            "price": "$396.04",
            "booked": true,
            "disable": false
          }, {
            "id": "38-169-7022",
            "seatNumber": 24,
            "price": "$428.45",
            "booked": true,
            "disable": false
          }, {
            "id": "01-682-7259",
            "seatNumber": 25,
            "price": "$338.38",
            "booked": true,
            "disable": true
          }, {
            "id": "61-447-2556",
            "seatNumber": 26,
            "price": "$363.62",
            "booked": false,
            "disable": true
          }, {
            "id": "59-986-7104",
            "seatNumber": 27,
            "price": "$491.96",
            "booked": false,
            "disable": true
          }, {
            "id": "89-356-6010",
            "seatNumber": 28,
            "price": "$302.16",
            "booked": true,
            "disable": true
          }, {
            "id": "90-825-5343",
            "seatNumber": 29,
            "price": "$440.40",
            "booked": true,
            "disable": false
          }, {
            "id": "83-213-5813",
            "seatNumber": 30,
            "price": "$307.45",
            "booked": true,
            "disable": false
          }, {
            "id": "98-747-6897",
            "seatNumber": 31,
            "price": "$398.27",
            "booked": true,
            "disable": false
          }, {
            "id": "65-147-6913",
            "seatNumber": 32,
            "price": "$372.55",
            "booked": true,
            "disable": false
          }, {
            "id": "05-926-5349",
            "seatNumber": 33,
            "price": "$369.76",
            "booked": true,
            "disable": true
          }, {
            "id": "76-060-7925",
            "seatNumber": 34,
            "price": "$320.68",
            "booked": false,
            "disable": false
          }, {
            "id": "63-435-7862",
            "seatNumber": 35,
            "price": "$375.39",
            "booked": false,
            "disable": true
          }, {
            "id": "85-373-7027",
            "seatNumber": 36,
            "price": "$342.86",
            "booked": false,
            "disable": true
          }, {
            "id": "12-314-8560",
            "seatNumber": 37,
            "price": "$418.59",
            "booked": false,
            "disable": true
          }, {
            "id": "83-642-5037",
            "seatNumber": 38,
            "price": "$312.92",
            "booked": false,
            "disable": false
          }, {
            "id": "61-180-7589",
            "seatNumber": 39,
            "price": "$398.66",
            "booked": true,
            "disable": false
          }, {
            "id": "07-291-4606",
            "seatNumber": 40,
            "price": "$358.48",
            "booked": false,
            "disable": false
          }, {
            "id": "79-974-6223",
            "seatNumber": 41,
            "price": "$330.48",
            "booked": false,
            "disable": true
          }, {
            "id": "00-033-3036",
            "seatNumber": 42,
            "price": "$387.87",
            "booked": false,
            "disable": false
          }, {
            "id": "66-929-6458",
            "seatNumber": 43,
            "price": "$347.93",
            "booked": true,
            "disable": true
          }, {
            "id": "22-958-8932",
            "seatNumber": 44,
            "price": "$328.83",
            "booked": true,
            "disable": true
          }, {
            "id": "13-310-6988",
            "seatNumber": 45,
            "price": "$435.53",
            "booked": false,
            "disable": false
          }, {
            "id": "41-272-8316",
            "seatNumber": 46,
            "price": "$316.77",
            "booked": false,
            "disable": true
          }, {
            "id": "16-765-7415",
            "seatNumber": 47,
            "price": "$420.82",
            "booked": true,
            "disable": true
          }, {
            "id": "86-751-7685",
            "seatNumber": 48,
            "price": "$448.06",
            "booked": false,
            "disable": false
          }, {
            "id": "93-394-5131",
            "seatNumber": 49,
            "price": "$442.77",
            "booked": true,
            "disable": true
          }, {
            "id": "97-938-6119",
            "seatNumber": 50,
            "price": "$365.19",
            "booked": true,
            "disable": false
          }]        
      },
      {
          id:"3",
          movieName:"Satyameva Jayate 2",
          describe:"In a vicious world, a patriotic, and single-minded Satya who dreams of a corrupt-free India, decides to take matters into his own hands.",
          age:"7+",
          img:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@like_202006280402.png,ox-24,oy-617,ow-29:ote-MzdrIGxpa2Vz,ots-29,otc-FFFFFF,oy-612,ox-70/et00113105-syalrzpcjt-portrait.jpg",
          start:"04:15",
          end:"06:30",
          language:"Hindi",
          categaries:['Action','Drama'],
          Ontheater:true,
          seats:[{
            "id": "10-541-2989",
            "seatNumber": 1,
            "price": "$332.62",
            "booked": true,
            "disable": true
          }, {
            "id": "18-395-6416",
            "seatNumber": 2,
            "price": "$408.85",
            "booked": true,
            "disable": false
          }, {
            "id": "90-855-1995",
            "seatNumber": 3,
            "price": "$404.17",
            "booked": true,
            "disable": false
          }, {
            "id": "85-389-6016",
            "seatNumber": 4,
            "price": "$464.59",
            "booked": false,
            "disable": false
          }, {
            "id": "21-379-0519",
            "seatNumber": 5,
            "price": "$450.24",
            "booked": false,
            "disable": true
          }, {
            "id": "56-940-5253",
            "seatNumber": 6,
            "price": "$477.55",
            "booked": false,
            "disable": true
          }, {
            "id": "50-443-9502",
            "seatNumber": 7,
            "price": "$378.91",
            "booked": false,
            "disable": false
          }, {
            "id": "75-675-5431",
            "seatNumber": 8,
            "price": "$303.50",
            "booked": true,
            "disable": false
          }, {
            "id": "06-120-5946",
            "seatNumber": 9,
            "price": "$350.36",
            "booked": false,
            "disable": false
          }, {
            "id": "22-568-3225",
            "seatNumber": 10,
            "price": "$424.83",
            "booked": false,
            "disable": false
          }, {
            "id": "27-807-8185",
            "seatNumber": 11,
            "price": "$301.45",
            "booked": false,
            "disable": true
          }, {
            "id": "15-527-6107",
            "seatNumber": 12,
            "price": "$361.36",
            "booked": false,
            "disable": false
          }, {
            "id": "82-636-0508",
            "seatNumber": 13,
            "price": "$484.73",
            "booked": false,
            "disable": true
          }, {
            "id": "49-157-6047",
            "seatNumber": 14,
            "price": "$450.98",
            "booked": false,
            "disable": false
          }, {
            "id": "12-535-7828",
            "seatNumber": 15,
            "price": "$466.07",
            "booked": false,
            "disable": true
          }, {
            "id": "15-920-6771",
            "seatNumber": 16,
            "price": "$410.23",
            "booked": true,
            "disable": true
          }, {
            "id": "23-265-3294",
            "seatNumber": 17,
            "price": "$335.58",
            "booked": true,
            "disable": true
          }, {
            "id": "19-609-6675",
            "seatNumber": 18,
            "price": "$405.33",
            "booked": false,
            "disable": false
          }, {
            "id": "40-681-1591",
            "seatNumber": 19,
            "price": "$375.13",
            "booked": false,
            "disable": false
          }, {
            "id": "03-079-0429",
            "seatNumber": 20,
            "price": "$420.54",
            "booked": false,
            "disable": true
          }, {
            "id": "23-468-7512",
            "seatNumber": 21,
            "price": "$491.89",
            "booked": false,
            "disable": false
          }, {
            "id": "83-809-7124",
            "seatNumber": 22,
            "price": "$338.85",
            "booked": true,
            "disable": true
          }, {
            "id": "26-283-0769",
            "seatNumber": 23,
            "price": "$451.21",
            "booked": false,
            "disable": true
          }, {
            "id": "94-271-0369",
            "seatNumber": 24,
            "price": "$357.96",
            "booked": false,
            "disable": true
          }, {
            "id": "41-134-9237",
            "seatNumber": 25,
            "price": "$398.64",
            "booked": false,
            "disable": false
          }, {
            "id": "05-323-0786",
            "seatNumber": 26,
            "price": "$495.88",
            "booked": true,
            "disable": true
          }, {
            "id": "04-516-0584",
            "seatNumber": 27,
            "price": "$460.08",
            "booked": true,
            "disable": false
          }, {
            "id": "93-327-2104",
            "seatNumber": 28,
            "price": "$425.19",
            "booked": true,
            "disable": false
          }, {
            "id": "37-742-8886",
            "seatNumber": 29,
            "price": "$451.16",
            "booked": true,
            "disable": true
          }, {
            "id": "63-671-3331",
            "seatNumber": 30,
            "price": "$379.44",
            "booked": true,
            "disable": false
          }, {
            "id": "47-742-4029",
            "seatNumber": 31,
            "price": "$357.53",
            "booked": true,
            "disable": false
          }, {
            "id": "99-152-6748",
            "seatNumber": 32,
            "price": "$326.75",
            "booked": true,
            "disable": false
          }, {
            "id": "11-962-4004",
            "seatNumber": 33,
            "price": "$463.76",
            "booked": false,
            "disable": true
          }, {
            "id": "79-876-8749",
            "seatNumber": 34,
            "price": "$304.98",
            "booked": true,
            "disable": true
          }, {
            "id": "34-596-0053",
            "seatNumber": 35,
            "price": "$380.18",
            "booked": true,
            "disable": false
          }, {
            "id": "56-775-4589",
            "seatNumber": 36,
            "price": "$422.85",
            "booked": true,
            "disable": true
          }, {
            "id": "06-725-1774",
            "seatNumber": 37,
            "price": "$331.21",
            "booked": true,
            "disable": true
          }, {
            "id": "78-912-9203",
            "seatNumber": 38,
            "price": "$465.92",
            "booked": false,
            "disable": true
          }, {
            "id": "25-417-4319",
            "seatNumber": 39,
            "price": "$490.95",
            "booked": false,
            "disable": true
          }, {
            "id": "77-526-6824",
            "seatNumber": 40,
            "price": "$498.94",
            "booked": true,
            "disable": true
          }, {
            "id": "58-092-6349",
            "seatNumber": 41,
            "price": "$468.51",
            "booked": true,
            "disable": true
          }, {
            "id": "32-005-0187",
            "seatNumber": 42,
            "price": "$388.45",
            "booked": false,
            "disable": false
          }, {
            "id": "92-872-1697",
            "seatNumber": 43,
            "price": "$339.35",
            "booked": true,
            "disable": true
          }, {
            "id": "27-875-7668",
            "seatNumber": 44,
            "price": "$496.53",
            "booked": false,
            "disable": true
          }, {
            "id": "01-133-6267",
            "seatNumber": 45,
            "price": "$414.23",
            "booked": false,
            "disable": false
          }, {
            "id": "49-954-7202",
            "seatNumber": 46,
            "price": "$423.44",
            "booked": false,
            "disable": true
          }, {
            "id": "93-576-7213",
            "seatNumber": 47,
            "price": "$312.19",
            "booked": false,
            "disable": false
          }, {
            "id": "94-741-2217",
            "seatNumber": 48,
            "price": "$338.85",
            "booked": false,
            "disable": true
          }, {
            "id": "78-366-6789",
            "seatNumber": 49,
            "price": "$417.40",
            "booked": false,
            "disable": true
          }, {
            "id": "71-974-0127",
            "seatNumber": 50,
            "price": "$351.03",
            "booked": true,
            "disable": true
          }, {
            "id": "10-173-3251",
            "seatNumber": 51,
            "price": "$341.89",
            "booked": true,
            "disable": false
          }, {
            "id": "00-110-1192",
            "seatNumber": 52,
            "price": "$420.92",
            "booked": true,
            "disable": true
          }, {
            "id": "00-858-0539",
            "seatNumber": 53,
            "price": "$426.09",
            "booked": false,
            "disable": false
          }, {
            "id": "25-416-1198",
            "seatNumber": 54,
            "price": "$379.63",
            "booked": false,
            "disable": false
          }, {
            "id": "45-831-0860",
            "seatNumber": 55,
            "price": "$396.32",
            "booked": true,
            "disable": false
          }, {
            "id": "71-262-5660",
            "seatNumber": 56,
            "price": "$379.56",
            "booked": true,
            "disable": true
          }, {
            "id": "10-203-8105",
            "seatNumber": 57,
            "price": "$319.10",
            "booked": true,
            "disable": false
          }, {
            "id": "93-847-1845",
            "seatNumber": 58,
            "price": "$338.87",
            "booked": true,
            "disable": true
          }, {
            "id": "80-928-5172",
            "seatNumber": 59,
            "price": "$397.23",
            "booked": false,
            "disable": true
          }, {
            "id": "02-269-8047",
            "seatNumber": 60,
            "price": "$355.45",
            "booked": true,
            "disable": false
          }, {
            "id": "63-259-8325",
            "seatNumber": 61,
            "price": "$444.02",
            "booked": false,
            "disable": false
          }, {
            "id": "39-424-9834",
            "seatNumber": 62,
            "price": "$458.95",
            "booked": true,
            "disable": true
          }, {
            "id": "19-365-5083",
            "seatNumber": 63,
            "price": "$333.10",
            "booked": false,
            "disable": false
          }, {
            "id": "82-564-3927",
            "seatNumber": 64,
            "price": "$425.74",
            "booked": false,
            "disable": false
          }, {
            "id": "59-834-1365",
            "seatNumber": 65,
            "price": "$423.89",
            "booked": false,
            "disable": false
          }, {
            "id": "32-411-0766",
            "seatNumber": 66,
            "price": "$485.06",
            "booked": true,
            "disable": false
          }, {
            "id": "22-645-6684",
            "seatNumber": 67,
            "price": "$493.51",
            "booked": false,
            "disable": true
          }, {
            "id": "81-136-9237",
            "seatNumber": 68,
            "price": "$418.44",
            "booked": false,
            "disable": true
          }, {
            "id": "11-155-1720",
            "seatNumber": 69,
            "price": "$301.01",
            "booked": false,
            "disable": false
          }, {
            "id": "85-045-9108",
            "seatNumber": 70,
            "price": "$395.13",
            "booked": false,
            "disable": true
          }, {
            "id": "16-201-5658",
            "seatNumber": 71,
            "price": "$338.90",
            "booked": false,
            "disable": false
          }, {
            "id": "60-106-0880",
            "seatNumber": 72,
            "price": "$320.66",
            "booked": true,
            "disable": false
          }, {
            "id": "35-338-8805",
            "seatNumber": 73,
            "price": "$350.34",
            "booked": false,
            "disable": false
          }, {
            "id": "38-696-2085",
            "seatNumber": 74,
            "price": "$473.68",
            "booked": false,
            "disable": true
          }, {
            "id": "72-992-0990",
            "seatNumber": 75,
            "price": "$324.28",
            "booked": true,
            "disable": true
          }, {
            "id": "22-711-9970",
            "seatNumber": 76,
            "price": "$442.97",
            "booked": true,
            "disable": false
          }, {
            "id": "70-124-4740",
            "seatNumber": 77,
            "price": "$339.25",
            "booked": true,
            "disable": true
          }, {
            "id": "56-221-1423",
            "seatNumber": 78,
            "price": "$452.33",
            "booked": false,
            "disable": false
          }, {
            "id": "93-226-3769",
            "seatNumber": 79,
            "price": "$415.80",
            "booked": true,
            "disable": false
          }, {
            "id": "96-467-7030",
            "seatNumber": 80,
            "price": "$442.44",
            "booked": false,
            "disable": true
          }, {
            "id": "89-472-7899",
            "seatNumber": 81,
            "price": "$307.17",
            "booked": true,
            "disable": true
          }, {
            "id": "71-334-4714",
            "seatNumber": 82,
            "price": "$497.86",
            "booked": true,
            "disable": false
          }, {
            "id": "44-130-6083",
            "seatNumber": 83,
            "price": "$386.57",
            "booked": true,
            "disable": true
          }, {
            "id": "96-755-5651",
            "seatNumber": 84,
            "price": "$448.48",
            "booked": true,
            "disable": false
          }, {
            "id": "00-652-4835",
            "seatNumber": 85,
            "price": "$412.79",
            "booked": false,
            "disable": true
          }, {
            "id": "87-148-0941",
            "seatNumber": 86,
            "price": "$377.02",
            "booked": false,
            "disable": false
          }, {
            "id": "92-185-9844",
            "seatNumber": 87,
            "price": "$499.45",
            "booked": true,
            "disable": false
          }, {
            "id": "15-018-9676",
            "seatNumber": 88,
            "price": "$387.63",
            "booked": false,
            "disable": true
          }, {
            "id": "32-367-8876",
            "seatNumber": 89,
            "price": "$320.24",
            "booked": true,
            "disable": true
          }, {
            "id": "27-442-2662",
            "seatNumber": 90,
            "price": "$335.00",
            "booked": false,
            "disable": false
          }, {
            "id": "77-529-8037",
            "seatNumber": 91,
            "price": "$342.30",
            "booked": true,
            "disable": false
          }, {
            "id": "53-015-6904",
            "seatNumber": 92,
            "price": "$403.38",
            "booked": false,
            "disable": false
          }, {
            "id": "94-613-3856",
            "seatNumber": 93,
            "price": "$485.53",
            "booked": false,
            "disable": true
          }, {
            "id": "31-377-5416",
            "seatNumber": 94,
            "price": "$490.82",
            "booked": true,
            "disable": true
          }, {
            "id": "09-717-9196",
            "seatNumber": 95,
            "price": "$405.45",
            "booked": false,
            "disable": true
          }, {
            "id": "39-998-0082",
            "seatNumber": 96,
            "price": "$410.88",
            "booked": false,
            "disable": false
          }, {
            "id": "37-633-2830",
            "seatNumber": 97,
            "price": "$448.61",
            "booked": false,
            "disable": false
          }, {
            "id": "95-026-6187",
            "seatNumber": 98,
            "price": "$457.87",
            "booked": true,
            "disable": false
          }, {
            "id": "00-971-4558",
            "seatNumber": 99,
            "price": "$493.69",
            "booked": true,
            "disable": true
          }, {
            "id": "39-194-2940",
            "seatNumber": 100,
            "price": "$363.64",
            "booked": true,
            "disable": true
          }]
      },
      {
          id:"4",
          movieName:"Sooryavanshi",
          describe:"Starting off from where Akshay Kumar`s character was introduced in Simmba, Sooryavanshi traces the acts and serious antics of DCP Veer Sooryavanshi, the chief of the Anti-Terrorism Squad in India.",
          age:"7+",
          img:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@heart_202006300400.png,ox-24,oy-617,ow-29:ote-ODMlICAxMjBrIHZvdGVz,ots-29,otc-FFFFFF,oy-612,ox-70/et00097952-dcgejsfjnm-portrait.jpg",
          start:"07:00",
          end:"09:00",
          language:"Hindi",
          categaries:['Action','Comedy','Drama'],
          Ontheater:true,
          seats:[{
            "id": "80-751-0260",
            "seatNumber": 1,
            "price": "$335.83",
            "booked": true,
            "disable": true
          }, {
            "id": "88-169-6282",
            "seatNumber": 2,
            "price": "$394.38",
            "booked": false,
            "disable": true
          }, {
            "id": "28-154-3137",
            "seatNumber": 3,
            "price": "$369.56",
            "booked": false,
            "disable": false
          }, {
            "id": "26-813-5287",
            "seatNumber": 4,
            "price": "$438.44",
            "booked": true,
            "disable": true
          }, {
            "id": "83-352-1401",
            "seatNumber": 5,
            "price": "$408.64",
            "booked": true,
            "disable": true
          }, {
            "id": "88-082-1357",
            "seatNumber": 6,
            "price": "$389.01",
            "booked": true,
            "disable": true
          }, {
            "id": "68-945-0574",
            "seatNumber": 7,
            "price": "$402.09",
            "booked": false,
            "disable": false
          }, {
            "id": "75-526-1348",
            "seatNumber": 8,
            "price": "$359.33",
            "booked": false,
            "disable": false
          }, {
            "id": "92-943-3368",
            "seatNumber": 9,
            "price": "$390.67",
            "booked": true,
            "disable": true
          }, {
            "id": "51-757-4653",
            "seatNumber": 10,
            "price": "$400.19",
            "booked": false,
            "disable": true
          }, {
            "id": "33-853-4546",
            "seatNumber": 11,
            "price": "$457.74",
            "booked": false,
            "disable": false
          }, {
            "id": "14-239-2412",
            "seatNumber": 12,
            "price": "$356.86",
            "booked": false,
            "disable": false
          }, {
            "id": "32-405-2270",
            "seatNumber": 13,
            "price": "$349.58",
            "booked": true,
            "disable": true
          }, {
            "id": "08-137-1724",
            "seatNumber": 14,
            "price": "$416.93",
            "booked": true,
            "disable": true
          }, {
            "id": "07-881-7978",
            "seatNumber": 15,
            "price": "$367.61",
            "booked": true,
            "disable": false
          }, {
            "id": "52-706-7204",
            "seatNumber": 16,
            "price": "$431.41",
            "booked": false,
            "disable": false
          }, {
            "id": "44-131-6112",
            "seatNumber": 17,
            "price": "$420.56",
            "booked": true,
            "disable": true
          }, {
            "id": "92-856-4371",
            "seatNumber": 18,
            "price": "$458.53",
            "booked": true,
            "disable": true
          }, {
            "id": "16-841-4649",
            "seatNumber": 19,
            "price": "$403.46",
            "booked": true,
            "disable": true
          }, {
            "id": "36-411-2310",
            "seatNumber": 20,
            "price": "$432.88",
            "booked": true,
            "disable": false
          }, {
            "id": "65-295-4832",
            "seatNumber": 21,
            "price": "$486.77",
            "booked": true,
            "disable": true
          }, {
            "id": "40-850-5087",
            "seatNumber": 22,
            "price": "$313.17",
            "booked": true,
            "disable": false
          }, {
            "id": "75-693-1206",
            "seatNumber": 23,
            "price": "$441.01",
            "booked": true,
            "disable": false
          }, {
            "id": "87-484-7081",
            "seatNumber": 24,
            "price": "$497.65",
            "booked": false,
            "disable": false
          }, {
            "id": "41-311-0646",
            "seatNumber": 25,
            "price": "$493.46",
            "booked": false,
            "disable": true
          }, {
            "id": "56-072-4873",
            "seatNumber": 26,
            "price": "$429.00",
            "booked": false,
            "disable": false
          }, {
            "id": "90-512-1893",
            "seatNumber": 27,
            "price": "$487.17",
            "booked": true,
            "disable": false
          }, {
            "id": "68-378-3767",
            "seatNumber": 28,
            "price": "$339.77",
            "booked": false,
            "disable": false
          }, {
            "id": "84-584-5029",
            "seatNumber": 29,
            "price": "$481.88",
            "booked": true,
            "disable": true
          }, {
            "id": "50-455-8479",
            "seatNumber": 30,
            "price": "$343.08",
            "booked": false,
            "disable": true
          }, {
            "id": "63-110-9066",
            "seatNumber": 31,
            "price": "$328.59",
            "booked": true,
            "disable": false
          }, {
            "id": "24-259-2779",
            "seatNumber": 32,
            "price": "$499.50",
            "booked": false,
            "disable": true
          }, {
            "id": "00-118-8325",
            "seatNumber": 33,
            "price": "$403.76",
            "booked": false,
            "disable": true
          }, {
            "id": "71-183-6636",
            "seatNumber": 34,
            "price": "$330.64",
            "booked": false,
            "disable": true
          }, {
            "id": "56-480-2854",
            "seatNumber": 35,
            "price": "$358.61",
            "booked": true,
            "disable": false
          }, {
            "id": "14-904-2230",
            "seatNumber": 36,
            "price": "$468.82",
            "booked": false,
            "disable": false
          }, {
            "id": "67-657-3567",
            "seatNumber": 37,
            "price": "$302.03",
            "booked": true,
            "disable": true
          }, {
            "id": "15-709-6198",
            "seatNumber": 38,
            "price": "$448.48",
            "booked": false,
            "disable": true
          }, {
            "id": "90-098-9370",
            "seatNumber": 39,
            "price": "$341.57",
            "booked": true,
            "disable": false
          }, {
            "id": "75-068-9548",
            "seatNumber": 40,
            "price": "$372.23",
            "booked": true,
            "disable": true
          }, {
            "id": "22-476-3641",
            "seatNumber": 41,
            "price": "$366.94",
            "booked": false,
            "disable": false
          }, {
            "id": "31-291-5083",
            "seatNumber": 42,
            "price": "$435.26",
            "booked": false,
            "disable": false
          }, {
            "id": "70-283-9660",
            "seatNumber": 43,
            "price": "$316.22",
            "booked": true,
            "disable": false
          }, {
            "id": "27-933-7747",
            "seatNumber": 44,
            "price": "$308.87",
            "booked": false,
            "disable": false
          }, {
            "id": "60-977-4256",
            "seatNumber": 45,
            "price": "$396.15",
            "booked": false,
            "disable": true
          }, {
            "id": "79-047-0282",
            "seatNumber": 46,
            "price": "$341.44",
            "booked": true,
            "disable": false
          }, {
            "id": "60-148-2212",
            "seatNumber": 47,
            "price": "$387.98",
            "booked": true,
            "disable": true
          }, {
            "id": "26-364-0698",
            "seatNumber": 48,
            "price": "$391.42",
            "booked": false,
            "disable": false
          }, {
            "id": "34-531-5195",
            "seatNumber": 49,
            "price": "$442.97",
            "booked": false,
            "disable": false
          }, {
            "id": "63-055-8390",
            "seatNumber": 50,
            "price": "$421.74",
            "booked": false,
            "disable": true
          }, {
            "id": "35-313-6696",
            "seatNumber": 51,
            "price": "$313.21",
            "booked": false,
            "disable": true
          }, {
            "id": "99-631-3126",
            "seatNumber": 52,
            "price": "$310.37",
            "booked": true,
            "disable": false
          }, {
            "id": "47-533-7368",
            "seatNumber": 53,
            "price": "$328.80",
            "booked": true,
            "disable": false
          }, {
            "id": "01-545-5375",
            "seatNumber": 54,
            "price": "$455.61",
            "booked": true,
            "disable": true
          }, {
            "id": "55-777-3468",
            "seatNumber": 55,
            "price": "$463.33",
            "booked": false,
            "disable": false
          }, {
            "id": "66-660-8039",
            "seatNumber": 56,
            "price": "$328.02",
            "booked": true,
            "disable": true
          }, {
            "id": "08-446-8199",
            "seatNumber": 57,
            "price": "$445.16",
            "booked": false,
            "disable": true
          }, {
            "id": "12-278-0653",
            "seatNumber": 58,
            "price": "$326.59",
            "booked": false,
            "disable": false
          }, {
            "id": "95-483-7549",
            "seatNumber": 59,
            "price": "$400.85",
            "booked": false,
            "disable": false
          }, {
            "id": "26-466-2672",
            "seatNumber": 60,
            "price": "$455.97",
            "booked": false,
            "disable": false
          }, {
            "id": "04-958-8202",
            "seatNumber": 61,
            "price": "$462.75",
            "booked": false,
            "disable": true
          }, {
            "id": "37-845-4972",
            "seatNumber": 62,
            "price": "$345.92",
            "booked": false,
            "disable": true
          }, {
            "id": "07-424-9684",
            "seatNumber": 63,
            "price": "$490.05",
            "booked": true,
            "disable": true
          }, {
            "id": "05-322-3831",
            "seatNumber": 64,
            "price": "$476.21",
            "booked": false,
            "disable": false
          }, {
            "id": "42-564-1125",
            "seatNumber": 65,
            "price": "$322.83",
            "booked": false,
            "disable": false
          }, {
            "id": "23-558-5621",
            "seatNumber": 66,
            "price": "$328.85",
            "booked": false,
            "disable": true
          }, {
            "id": "20-427-6426",
            "seatNumber": 67,
            "price": "$463.83",
            "booked": true,
            "disable": true
          }, {
            "id": "88-729-3279",
            "seatNumber": 68,
            "price": "$367.62",
            "booked": true,
            "disable": false
          }, {
            "id": "67-307-2509",
            "seatNumber": 69,
            "price": "$423.42",
            "booked": true,
            "disable": false
          }, {
            "id": "98-578-4029",
            "seatNumber": 70,
            "price": "$478.41",
            "booked": false,
            "disable": false
          }, {
            "id": "76-362-8378",
            "seatNumber": 71,
            "price": "$339.14",
            "booked": false,
            "disable": false
          }, {
            "id": "72-378-0308",
            "seatNumber": 72,
            "price": "$329.95",
            "booked": true,
            "disable": true
          }, {
            "id": "25-555-8238",
            "seatNumber": 73,
            "price": "$450.27",
            "booked": true,
            "disable": false
          }, {
            "id": "67-439-4375",
            "seatNumber": 74,
            "price": "$486.54",
            "booked": false,
            "disable": false
          }, {
            "id": "06-895-0513",
            "seatNumber": 75,
            "price": "$461.92",
            "booked": true,
            "disable": true
          }, {
            "id": "35-620-1892",
            "seatNumber": 76,
            "price": "$424.06",
            "booked": true,
            "disable": true
          }, {
            "id": "02-769-3999",
            "seatNumber": 77,
            "price": "$417.22",
            "booked": false,
            "disable": false
          }, {
            "id": "09-067-9171",
            "seatNumber": 78,
            "price": "$449.10",
            "booked": true,
            "disable": false
          }, {
            "id": "00-814-3390",
            "seatNumber": 79,
            "price": "$399.38",
            "booked": true,
            "disable": true
          }, {
            "id": "22-946-8771",
            "seatNumber": 80,
            "price": "$415.01",
            "booked": true,
            "disable": true
          }]
          
      },
      {
          id:"5",
          movieName:"Venom: Let There Be Carnage",
          describe:"When deranged serial killer Cletus Kasady becomes host to an alien symbiote, Eddie Brock and Venom must put aside their differences to stop his reign of terror.",
          age:"10+",
          img:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:oi-discovery-catalog@@icons@@heart_202006300400.png,ox-24,oy-617,ow-29:ote-ODElICA1M2sgdm90ZXM%3D,ots-29,otc-FFFFFF,oy-612,ox-70/et00122532-htzdezbpke-portrait.jpg",
          start:"N/A",
          end:"N/A",
          language:"English,Hindi,Tamil,Telugu",
          categaries:['Action','Horror','Sci-Fi','Thriller'],
          Ontheater:false,
          seats:['Not Available Now']
      }

    ]

  
